# Generated by Django 2.0.9 on 2018-12-25 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.IntegerField(primary_key=True, serialize=False)),
                ('codigoEmpleado', models.CharField(max_length=7)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrePersona', models.CharField(max_length=50)),
                ('apellidoPersona', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('idPlaza', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrePlaza', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlazaEmpleado',
            fields=[
                ('idPlazaEmpleado', models.IntegerField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Empleado')),
                ('plaza', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Plaza')),
            ],
        ),
        migrations.CreateModel(
            name='PuestoUnidad',
            fields=[
                ('idPuestoUnidad', models.IntegerField(primary_key=True, serialize=False)),
                ('puestoUnidadClaseId', models.IntegerField()),
                ('nombrePuestoUnidad', models.CharField(max_length=50)),
                ('puestoJefeId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('idUnidad', models.IntegerField(primary_key=True, serialize=False)),
                ('codigoUnidad', models.CharField(max_length=10)),
                ('nombreUnidad', models.CharField(max_length=75)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='puestounidad',
            name='idUnidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Unidad'),
        ),
        migrations.AddField(
            model_name='plaza',
            name='idUnidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Unidad'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='idPersona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Persona'),
        ),
    ]
