# Generated by Django 2.0.9 on 2018-12-26 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bandeja',
            fields=[
                ('idBandeja', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreBandeja', models.CharField(max_length=10)),
                ('descripcionBandeja', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('idCaja', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCaja', models.CharField(max_length=10)),
                ('descripcionCaja', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('idBandeja', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Bandeja')),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('idCarro', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCarro', models.CharField(max_length=10)),
                ('descripcionCarro', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoExpediente',
            fields=[
                ('idEstadoExpediente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreEstadoExpediente', models.CharField(max_length=50)),
                ('descripcionEstadoExpediente', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPrestamo',
            fields=[
                ('idEstadoPrestamo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreEstadoPrestamo', models.CharField(max_length=50)),
                ('descripcionEstadoPrestamo', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTransferencia',
            fields=[
                ('idEstadoTransferencia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreEstadoTransferencia', models.CharField(max_length=50)),
                ('descripcionEstadoTransferencia', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('idEstante', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreEstante', models.CharField(max_length=10)),
                ('descripcionEstante', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('idCarro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Carro')),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('idExpediente', models.IntegerField(primary_key=True, serialize=False)),
                ('codExpediente', models.IntegerField()),
                ('nombreExpediente', models.CharField(max_length=100)),
                ('DescripcionExpediente', models.CharField(max_length=200)),
                ('fechaIngresoExp', models.DateField()),
                ('fechaInicioExp', models.DateField()),
                ('fechaFinExp', models.DateField()),
                ('esOriginalExp', models.BooleanField(default=True)),
                ('ubicacionDescripcion', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fechaExpiracion', models.DateField()),
                ('migradoAtom', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExpedienteCaja',
            fields=[
                ('idExpedienteCaja', models.IntegerField(primary_key=True, serialize=False)),
                ('idCaja', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Caja')),
                ('idEstadoExpediente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.EstadoExpediente')),
                ('idExpediente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Expediente')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('idPrestamo', models.IntegerField(primary_key=True, serialize=False)),
                ('codigoPrestamo', models.CharField(max_length=25)),
                ('motivoPrestamo', models.CharField(max_length=200)),
                ('fechaPrestamo', models.DateField()),
                ('fechaProgramadaDevolucion', models.DateField()),
                ('fechaDevolucionPrestamo', models.DateField()),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Empleado')),
                ('idEstadoPrestamo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.EstadoPrestamo')),
                ('idUnidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Unidad')),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoExpediente',
            fields=[
                ('idPrestamoExpediente', models.IntegerField(primary_key=True, serialize=False)),
                ('devuelto', models.BooleanField(default=False)),
                ('idExpediente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Expediente')),
                ('idPrestamo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Prestamo')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('idSerie', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreSerie', models.CharField(max_length=200)),
                ('DescripcionSerie', models.CharField(max_length=200)),
                ('codSerie', models.CharField(max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('idSeriePadre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SerieExpediente',
            fields=[
                ('idSerieExpediente', models.IntegerField(primary_key=True, serialize=False)),
                ('esPrincipal', models.BooleanField(default=False)),
                ('idExpediente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Expediente')),
                ('idSerie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Serie')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('idTransferencia', models.IntegerField(primary_key=True, serialize=False)),
                ('codigoTransferencia', models.CharField(max_length=25)),
                ('fechaTransferencia', models.DateField()),
                ('motivoTransferencia', models.CharField(max_length=200)),
                ('observacionesTransferencia', models.CharField(max_length=200)),
                ('fechaResolucionTransferencia', models.DateField()),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Empleado')),
                ('idEstadoTransferencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.EstadoTransferencia')),
                ('idUnidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('idZona', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreZona', models.CharField(max_length=10)),
                ('descripcionZona', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='expediente',
            name='idTransferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Transferencia'),
        ),
        migrations.AddField(
            model_name='carro',
            name='idZona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Zona'),
        ),
        migrations.AddField(
            model_name='bandeja',
            name='idEstante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Estante'),
        ),
    ]
