# Generated by Django 2.0.9 on 2019-01-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20181226_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='idCarro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zona',
            name='idZona',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
